export const users = [
  {
    id: "12uda8131nae",
    name: "Mark McCoy",
    dealName: "Deal Name Title",
    size: "Large",
    quantity: "2",
    amount: "469.00",
    orderDate: "12/01/2021",
    status: "Not Picked",
  },
  {
    id: "61uda85g1nae",
    name: "John Doe",
    dealName: "Deal Name Title",
    size: "Large",
    quantity: "2",
    amount: "469.00",
    orderDate: "12/01/2021",
    status: "Picked",
  },
  {
    id: "41uda312nnsdae",
    name: "Arlene McCoy",
    dealName: "Deal Name Title",
    size: "Large",
    quantity: "2",
    amount: "469.00",
    orderDate: "12/01/2021",
    status: "Not Picked",
  },
  {
    id: "12uda813sf1nae",
    name: "Mark McCoy",
    dealName: "Deal Name Title",
    size: "Large",
    quantity: "2",
    amount: "469.00",
    orderDate: "12/01/2021",
    status: "Not Picked",
  },
  {
    id: "61uda85gdfs1nae",
    name: "John Doe",
    dealName: "Deal Name Title",
    size: "Large",
    quantity: "2",
    amount: "469.00",
    orderDate: "12/01/2021",
    status: "Picked",
  },
  {
    id: "41uda312nnsasdae",
    name: "Arlene McCoy",
    dealName: "Deal Name Title",
    size: "Large",
    quantity: "2",
    amount: "469.00",
    orderDate: "12/01/2021",
    status: "Not Picked",
  },
];
