// app/(main)/layout.jsx
import "../globals.css";
import Script from "next/script";

export const metadata = {
  title: "Plenti",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <>
      {/* Google Translate Element */}
      <div id="google_translate_element" style={{ display: "none" }}></div>
      
      {children}
      
      {/* Google Translate Scripts */}
      <Script
        strategy="afterInteractive"
        src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
      />
      <Script
        id="google-translate-init"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            function googleTranslateElementInit() {
              new google.translate.TranslateElement({
                pageLanguage: 'en',
                autoDisplay: false
              }, 'google_translate_element');
            }
          `,
        }}
      />
    </>
  );
}