// app/(auth)/layout.jsx
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Plenti",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className={inter.className}>
      {children}
    </div>
  );
}