import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>Auth Layout</h1>
        </header>
        <main>{children}</main>
        <footer>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
