import { Inter } from "next/font/google";
import "../globals.css";

import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Plenti",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors position="top-center" />

        <>{children}</>
      </body>
    </html>
  );
}
